### ISSUE TITLE
SageMaker Training Jobsの上限緩和申請の制限について

### ISSUE THREAD

**Issue by KENSUKESATOU** [aws-samples/bokete-denshosen#1]
表題について一応確認させていただきたいです。

LIMIT_INCREASE.md 4.のⅲでSageMaker Training Jobsの上限緩和申請の制限を選択しています。
記載は以下のようになっています。

```
制限「ml.g4dn.2xlarge」(.xlarge ではなく .4xlarge を利用) を選択
```

`ml.g4dn.2xlarge`であり、`ml.g4dn.4xlarge`ではない認識ですが正しいでしょうか？

**Comment by KENSUKESATOU** [comment]
よく見たら冒頭に`SageMaker Training (ml.g4dn.2xlarge)`と記載されていますね。
上記認識で正しいことがわかりました。
失礼しました。コメントはクローズします。

**Comment by hariby** [comment]
コメントありがとうございます。
`.2xlarge` でも `.4xlarge` でも、どちらでも問題なく動くことを確認したので、小さい方の `.2xlarge` に統一しようとして一部古い記述が残っていました。
該当箇所は修正済みです。
